#!/usr/bin/env python3
"""Generate (and compile) the type descriptions the overlap extension ships.

libmutter is built with hidden visibility, but the test-export macro expands to a real
export, so the four symbols the extension needs are ordinary dynamic symbols in the
shipped library -- absent from the introspection data, not from the library.  A GNOME
Shell extension can prepend its own search path and load a type description it ships
itself, which is what these files are.

Two properties of what is emitted here matter more than anything else in this tree:

**No pointer is ever declared as a pointer.**  Every pointer field in Mutter's private
structures is declared `guint64`, so reading one yields a *number* and gjs never
dereferences anything on our behalf.  Stepping from one struct to the next goes through
`g_memdup2(ptr, n)` -- a bounded copy of exactly n bytes -- and `g_strndup(ptr, n)` for
the connector strings, which lets the extension range-check the number against
`/proc/self/maps` before any address is read at all.  A wrong offset then produces
garbage or a refusal, not a SIGSEGV; with pointers declared as pointers it produced a
dead gnome-shell (measured, GNOME 50.1, docs/Technical.md section 6).

**Nothing that can write ~/.config/monitors.xml is declared.**
`meta_monitor_config_manager_save_current()` is not in the file, and neither is any
other `*save*` symbol, so no code in the extension can reach the writer even by
mistake.  `tests/test_gnome_overlap.py` asserts that about the shipped .gir and about
the shipped .typelib bytes.

The layout below is measured, not assumed (docs/Technical.md section 6): `parent_config`
and `switch_config` were proved with sentinels written through the exported accessors.
`logical_monitor_configs` is at offset 40 on both mutter 14 and mutter 18; the tail and
the total size are not the same, which is exactly why there is one description per
generation and why the extension refuses to run one against the other.

    offset  mutter 14 (GNOME 46)      mutter 18 (GNOME 50)
    0..23   GObject                   GObject
    24      parent_config             parent_config
    32      key                       key
    40      logical_monitor_configs   logical_monitor_configs
    48      disabled_monitor_specs    disabled_monitor_specs
    56      flags                     (unused)
    60      layout_mode               (unused)
    64      switch_config             (unused)
    68      padding                   layout_mode
    72      --                        switch_config
    76      --                        padding
    size    72                        80

Usage:  python3 gnome/overlap-typelib/gen-gir.py [OUTDIR]
        (OUTDIR defaults to gnome/w11-overlap@w11/typelib)
        python3 gnome/overlap-typelib/gen-gir.py --check
        python3 gnome/overlap-typelib/gen-gir.py --from-header PATH [--shell N]

What it generates it generates *from the table*,
gnome/w11-overlap@w11/generations.json: one .gir and one
.typelib per record, and metadata.json's `shell-version` list.  So adding a
GNOME release is a record in that file (and its twin, GENERATIONS in
wxrandr/gnome_overlap.py) plus one run of this script -- there is no fourth
place to forget.

Needs `g-ir-compiler` (Ubuntu: libgirepository1.0-dev).  The compiled typelibs are
checked in because no desktop has that package installed; `--check` recompiles and
compares, which is how CI notices a .gir edited without a rebuild.  Its exit status
has three values, because "nothing disagreed" and "nothing was compared" are not the
same answer: 0 every namespace compared and agreed, 1 something is stale, 2 the
comparison could not be made here (no GIRepository to read a typelib with).  A CI
that treats 2 as a pass is a CI that ships whatever the .gir happened to say.

`--from-header` is the answer to a `typelib` or `sentinel` refusal after a GNOME
upgrade, and the only route by which a new generation should ever be added.  It reads
mutter's own `src/backends/meta-monitor-config-manager.h` -- the release's source, not
the running compositor -- lays `struct _MetaMonitorsConfig` out under the x86-64 rules
and prints the offsets, the instance size and the two numbers a record needs.  With
`--shell N` it compares those against the record shipped for GNOME N and says whether
they agree -- or, when there is no such record, prints the record to add and the two
files to add it to.

**It derives from source and never from a live libmutter, and that is the whole
point.**  A description generated by asking the compositor about itself would agree
with the compositor by construction: `struct-size` would pass because it was told the
size, and `sentinel` could only be satisfied by searching offsets until the marker
turned up, which is a search that confirms itself.  The independence of the shipped
description from the build it is checked against is what makes those two checks mean
anything -- it is why a wrong-generation description was caught before a byte was read
(measured on 24.04 and 26.04) -- and self-derivation would spend it to save a human
one afternoon per GNOME release.  So: derive the numbers here, from the release's
header, then prove them on a three-head VM as docs/Technical.md section 6 describes,
and only then add the generation to the four allowlists.
"""

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
EXT_DIR = os.path.join(os.path.dirname(HERE), "w11-overlap@w11")

#: THE TABLE, and this script no longer has one of its own.  It reads
#: `gnome/w11-overlap@w11/generations.json` -- the same file the
#: extension reads at run time -- so that a new GNOME is a record there and not
#: an edit here as well.
#:
#: What a record has to carry is spelled out in that file.  The two fields this
#: script uses are `namespace` (what the description is called) and `tail_slots`
#: (4-byte slots between `disabled_monitor_specs` and `layout_mode`, which is
#: the whole of what differs between the shipped descriptions and is what
#: `--from-header` derives from a release's own source).
#:
#: `soname` is NOT one of them, and nothing generated here names a library: see
#: the note at the top of HEAD below.  A description is a layout, the symbols
#: resolve out of gnome-shell's own global scope, and `soname` is only ever
#: matched against /proc/self/maps by the extension, to say which libmutter is
#: actually mapped.  It is written out in the record rather than composed from a
#: number because through GNOME 50 libmutter's API version was a counter of its
#: own and mutter 51 made it the GNOME major instead
#: (`libmutter_api_version = '51'`), so `libmutter-%d.so.0` describes the two
#: builds it was written for and nothing after them.  This comment said the
#: opposite until 0.4.1, which is an invitation to a maintainer to "put the
#: shared library back" -- the one edit that has actually killed a session here.
TABLE_PATH = os.path.join(EXT_DIR, "generations.json")
TABLE_FIELDS = ("shell_major", "libmutter", "soname", "meta_typelib",
                "namespace", "struct_size", "tail_slots")


def load_table(path=TABLE_PATH):
    """The generations, oldest first.  A record missing a field is an error
    naming the field: half a record is how a description gets shipped under the
    wrong name."""
    with open(path, encoding="utf-8") as fh:
        table = json.load(fh)
    records = sorted(table.get("generations") or [], key=lambda g: g["shell_major"])
    if not records:
        raise SystemExit("gen-gir: %s names no generations" % path)
    for g in records:
        for f in TABLE_FIELDS:
            if g.get(f) is None:
                raise SystemExit("gen-gir: %s: the GNOME %s record has no %s"
                                 % (path, g.get("shell_major"), f))
    return records

HEAD = '''<?xml version="1.0"?>
<!-- GENERATED by gnome/overlap-typelib/gen-gir.py -- do not edit by hand.
     Mutter {gen}'s private monitor-configuration structures, described so that no
     pointer in them is ever followed by the type system.  See that script.

     NO shared-library, and that is deliberate (0.4, measured on GNOME 51): a
     description here is a *layout*, not a binding to one file name.  A
     shared-library attribute makes GIRepository dlopen exactly that file, and
     a forced run on a new GNOME picks a description by struct size -- so the
     file name inside it is the one thing already known to be wrong, and
     libmutter-18.so.0 is not there on a machine carrying libmutter-51.so.0.
     The dlopen fails, and gjs then *aborts the process* on the first call
     through the description (assertion ffi_arg_pos == ffi_argc), which on
     Wayland is the whole session.  With no shared-library the symbols resolve
     out of gnome-shell's own global scope, where libmutter already is, and a
     symbol that is genuinely missing throws catchably instead.  Which library
     is mapped is proved from /proc/self/maps by the extension, which is where
     a file name belongs. -->
<repository version="1.2"
            xmlns="http://www.gtk.org/introspection/core/1.0"
            xmlns:c="http://www.gtk.org/introspection/c/1.0"
            xmlns:glib="http://www.gtk.org/introspection/glib/1.0">
  <include name="GObject" version="2.0"/>
  <namespace name="{ns}" version="1.0"
             c:identifier-prefixes="Meta" c:symbol-prefixes="meta">

    <!-- MetaMonitorsConfig.  Every pointer is a guint64: a number, never a
         dereference. -->
    <record name="ConfigN" c:type="MetaMonitorsConfigN">
      <field name="g_class" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="ref_count" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="qdata" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="parent_config" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="key" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="logical_monitor_configs" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="disabled_monitor_specs" writable="1"><type name="guint64" c:type="guint64"/></field>
{tail}      <field name="layout_mode" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="switch_config" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="tail_pad" writable="1"><type name="gint" c:type="gint"/></field>
    </record>

    <!-- GList -->
    <record name="NodeN" c:type="MetaNodeN">
      <field name="data" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="next" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="prev" writable="1"><type name="guint64" c:type="guint64"/></field>
    </record>

    <!-- MetaLogicalMonitorConfig.  x is at +0 and y at +4: the only two words
         this extension ever writes. -->
    <record name="LMCN" c:type="MetaLMCN">
      <field name="x" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="y" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="width" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="height" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="monitor_configs" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="transform" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="scale" writable="1"><type name="gfloat" c:type="gfloat"/></field>
      <field name="is_primary" writable="1"><type name="gboolean" c:type="gboolean"/></field>
      <field name="is_presentation" writable="1"><type name="gboolean" c:type="gboolean"/></field>
    </record>

    <!-- MetaMonitorConfig -->
    <record name="MCN" c:type="MetaMCN">
      <field name="monitor_spec" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="mode_spec" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="enable_underscanning" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="pad" writable="1"><type name="gint" c:type="gint"/></field>
    </record>

    <!-- MetaMonitorSpec -->
    <record name="MSN" c:type="MetaMSN">
      <field name="connector" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="vendor" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="product" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="serial" writable="1"><type name="guint64" c:type="guint64"/></field>
    </record>

'''

TAIL_FIELD = ('      <field name="u{off}" writable="1">'
              '<type name="gint" c:type="gint"/></field>\n')


def _memdup(name, ret):
    """g_memdup2(number, n) -> a copy of exactly n bytes, read as `ret`.

    KNOWN LEAK, and a deliberate one for now: the return is declared
    `transfer-ownership="none"`, so gjs reads the fields out of the copy and
    frees nothing -- 72 or 80 bytes per struct walked, a few hundred bytes per
    Probe or ApplyOverlap, in a process (gnome-shell) that lives for the
    session.  A user who ran this a thousand times would be out well under a
    megabyte.  It is not "full" because these are plain records with no
    registered free function and the copy's address is what the range checks are
    built on; the fix is an `fr` (`g_free`, taking the guint64 the extension
    already holds) called after each copy in extension.js, which is a change to
    the extension's read path and wants measuring on a live compositor first.
    tests/test_overlap_force.py TheDescriptionNamesNoLibrary holds the gap open.
    """
    return f'''    <function name="{name}" c:identifier="g_memdup2">
      <return-value transfer-ownership="none"><type name="{ret}" c:type="gpointer"/></return-value>
      <parameters>
        <parameter name="mem" transfer-ownership="none"><type name="guint64" c:type="guint64"/></parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>
'''


BODY = (
    _memdup('dup_cfg', 'ConfigN')
    + _memdup('dup_node', 'NodeN')
    + _memdup('dup_lmc', 'LMCN')
    + _memdup('dup_mc', 'MCN')
    + _memdup('dup_ms', 'MSN')
    + '''    <!-- a bounded copy of at most n bytes of a string.  g_strndup returns
         freshly allocated memory, so the caller owns it: declared "none" the
         string was converted to a JS value and then leaked, one connector name
         per monitor per read. -->
    <function name="strn" c:identifier="g_strndup">
      <return-value transfer-ownership="full"><type name="utf8" c:type="char*"/></return-value>
      <parameters>
        <parameter name="s" transfer-ownership="none"><type name="guint64" c:type="guint64"/></parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>

    <!-- the address of an object, as a number (g_object_ref returns its argument);
         every addr() is balanced by an unref_addr() -->
    <function name="addr" c:identifier="g_object_ref">
      <return-value transfer-ownership="none"><type name="guint64" c:type="guint64"/></return-value>
      <parameters><parameter name="o" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="unref_addr" c:identifier="g_object_unref">
      <return-value transfer-ownership="none"><type name="none" c:type="void"/></return-value>
      <parameters><parameter name="p" transfer-ownership="none"><type name="guint64" c:type="gpointer"/></parameter></parameters>
    </function>

    <!-- reads offset 0 only; GTypeInstance's first word is frozen ABI -->
    <function name="type_name" c:identifier="g_type_name_from_instance">
      <return-value transfer-ownership="none"><type name="utf8" c:type="char*"/></return-value>
      <parameters><parameter name="o" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>

    <!-- the exported-but-not-introspected monitor configuration API -->
    <function name="get_config_manager" c:identifier="meta_monitor_manager_get_config_manager">
      <return-value transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="get_current" c:identifier="meta_monitor_config_manager_get_current">
      <return-value transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="create_linear" c:identifier="meta_monitor_config_manager_create_linear">
      <return-value transfer-ownership="full"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="get_switch_config" c:identifier="meta_monitors_config_get_switch_config">
      <return-value transfer-ownership="none"><type name="gint" c:type="gint"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="set_switch_config" c:identifier="meta_monitors_config_set_switch_config">
      <return-value transfer-ownership="none"><type name="none" c:type="void"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="v" transfer-ownership="none"><type name="gint" c:type="gint"/></parameter></parameters>
    </function>
    <function name="verify" c:identifier="meta_verify_monitors_config" throws="1">
      <return-value transfer-ownership="none"><type name="gboolean" c:type="gboolean"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="apply" c:identifier="meta_monitor_manager_apply_monitors_config" throws="1">
      <return-value transfer-ownership="none"><type name="gboolean" c:type="gboolean"/></return-value>
      <parameters><parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="method" transfer-ownership="none"><type name="gint" c:type="gint"/></parameter></parameters>
    </function>

    <!-- the write: four bytes at an address the reader has already range-checked -->
    <function name="wr" c:identifier="memcpy">
      <return-value transfer-ownership="none"><type name="guint64" c:type="gpointer"/></return-value>
      <parameters>
        <parameter name="dest" transfer-ownership="none"><type name="guint64" c:type="gpointer"/></parameter>
        <parameter name="src" transfer-ownership="none">
          <array c:type="gpointer" length="2"><type name="guint8" c:type="guint8"/></array>
        </parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>
  </namespace>
</repository>
'''
)

# -- deriving a layout from mutter's own header -------------------------------
#
# The x86-64 System V rules, over the handful of types this one struct uses.  A
# type this table does not know is an error and not a guess: the whole value of
# doing the arithmetic here rather than by hand is that it cannot quietly get a
# size wrong, and an unknown type is exactly where a hand derivation goes wrong.
# `--int NAME` adds a 4-byte enum for a header that introduces one.
SIZES = {
    "GObject": (24, 8),                 # GTypeInstance* + ref_count + qdata
    "gboolean": (4, 4), "gint": (4, 4), "int": (4, 4), "guint": (4, 4),
    "unsigned int": (4, 4), "unsigned": (4, 4), "uint32_t": (4, 4),
    "gfloat": (4, 4), "float": (4, 4),
    "gsize": (8, 8), "guint64": (8, 8), "gint64": (8, 8),
    # mutter's own enums, which are ints: named one by one, because "it starts
    # with Meta" is true of the structs as well
    "MetaMonitorsConfigFlag": (4, 4),
    "MetaLogicalMonitorLayoutMode": (4, 4),
    "MetaMonitorSwitchConfigType": (4, 4),
}


def strip_comments(text: str) -> str:
    out, i, n = [], 0, len(text)
    while i < n:
        if text.startswith("/*", i):
            j = text.find("*/", i + 2)
            i = n if j < 0 else j + 2
        elif text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


def struct_fields(header_text: str, name: str = "_MetaMonitorsConfig") -> list:
    """[(type, field name, is pointer)] for one C struct in a header."""
    text = strip_comments(header_text)
    # A word boundary, and not `find`: `struct _MetaMonitorsConfig` is a prefix
    # of `struct _MetaMonitorsConfigKey`, which mutter's real header declares
    # first -- so a plain find lays out the wrong struct and then reports that
    # the head of it has moved.  Measured against mutter 51's own header, where
    # it made the documented `--from-header` route fail on the first try.
    m = re.search(r"\bstruct\s+%s\b" % re.escape(name), text)
    if m is None:
        raise SystemExit("gen-gir: no `struct %s` in that header" % name)
    at = m.start()
    open_at = text.index("{", at)
    close_at = text.index("}", open_at)
    fields = []
    for decl in text[open_at + 1:close_at].split(";"):
        decl = " ".join(decl.split())
        if not decl:
            continue
        if "(" in decl or "[" in decl:
            raise SystemExit("gen-gir: %s: this reads function pointers and arrays no "
                             "better than a human does: %s" % (name, decl))
        pointer = "*" in decl
        words = decl.replace("*", " ").split()
        if len(words) < 2:
            raise SystemExit("gen-gir: %s: cannot read the field `%s`" % (name, decl))
        fields.append((" ".join(words[:-1]), words[-1], pointer))
    return fields


def layout(fields: list) -> tuple:
    """(rows, instance size) for a field list, laid out the way the compiler does.

    rows are (offset, size, type, name)."""
    off, align_max, rows = 0, 1, []
    for ctype, fname, pointer in fields:
        if pointer:
            size = align = 8
        elif ctype in SIZES:
            size, align = SIZES[ctype]
        else:
            raise SystemExit(
                "gen-gir: `%s %s` is a type this does not know the size of.  Add it to "
                "SIZES (or pass --int %s if it is an enum) rather than guessing: a "
                "wrong size here is a wrong offset in a live compositor."
                % (ctype, fname, ctype))
        off = (off + align - 1) // align * align
        rows.append((off, size, ctype + (" *" if pointer else ""), fname))
        off += size
        align_max = max(align_max, align)
    return rows, (off + align_max - 1) // align_max * align_max


#: What the shipped description assumes about every generation, and what
#: `--from-header` refuses to paper over.  If a release breaks one of these the
#: description's *shape* no longer applies, not just its numbers, and the .gir in
#: this directory has to be rewritten by a human who has read the new struct.
SHAPE = [(0, "parent"), (24, "parent_config"), (32, "key"),
         (40, "logical_monitor_configs"), (48, "disabled_monitor_specs")]


def build_from_header(text: str) -> tuple:
    """((soname-less) BUILDS value, rows, size) for a mutter header.

    Returns (ints, rows, size): `ints` is the number of 4-byte slots the
    description fills between `disabled_monitor_specs` and `layout_mode`, which is
    the only thing BUILDS carries besides the soname."""
    rows, size = layout(struct_fields(text))
    at = {name: (off, sz) for off, sz, _t, name in rows}
    for off, name in SHAPE:
        if at.get(name, (None,))[0] != off:
            raise SystemExit(
                "gen-gir: this header puts %s at %s, not %d.  The shipped description "
                "assumes the head of this struct is unchanged; a release that moves it "
                "needs a new .gir written by hand, not a new number."
                % (name, at.get(name, ("absent",))[0], off))
    for name in ("layout_mode", "switch_config"):
        if name not in at or at[name][1] != 4:
            raise SystemExit("gen-gir: no 4-byte %s in this struct" % name)
    lm, sw = at["layout_mode"][0], at["switch_config"][0]
    if sw != lm + 4:
        raise SystemExit("gen-gir: switch_config is at %d, not straight after "
                         "layout_mode at %d" % (sw, lm))
    if lm < 56 or (lm - 56) % 4:
        raise SystemExit("gen-gir: layout_mode is at %d; the description can only "
                         "describe the gap before it in whole 4-byte slots" % lm)
    return (lm - 56) // 4, rows, size


def report_header(path: str, shell) -> int:
    text = open(path, encoding="utf-8", errors="replace").read()
    ints, rows, size = build_from_header(text)
    table = load_table()
    print("%s" % path)
    for off, sz, ctype, name in rows:
        print("  %3d  %2d  %s %s" % (off, sz, ctype, name))
    print("  instance size %d" % size)
    print("  the two numbers a record needs:  \"struct_size\": %d, \"tail_slots\": %d"
          % (size, ints))
    if shell is None:
        print("  (pass --shell N to compare this against the record shipped for "
              "GNOME N, or to be told how to add it)")
        return 0
    shell = int(shell)
    have = {g["shell_major"]: g for g in table}
    if shell not in have:
        print("  GNOME %d is not in the table.  Adding it is one record in each of"
              % shell)
        print("      %s" % TABLE_PATH)
        print("      wxrandr/gnome_overlap.py  (GENERATIONS)")
        print("  and nothing anywhere else.  The record:")
        print("      {\"shell_major\": %d, \"libmutter\": \"<as in the soname>\","
              % shell)
        print("       \"soname\": \"<the file gnome-shell maps, from /proc/<pid>/maps>\",")
        print("       \"meta_typelib\": \"<GIRepository's version for Meta>\",")
        print("       \"namespace\": \"W11Overlap<the same>\",")
        print("       \"struct_size\": %d, \"tail_slots\": %d," % (size, ints))
        print("       \"measured_on\": \"<the machine you proved this on>\"}")
        print("  Every name is written out because none of them can be computed: "
              "mutter 51")
        print("  renumbered libmutter's API version to the GNOME major, so the "
              "arithmetic")
        print("  the first two records happened to follow is gone.")
        print("  Then run this script with no arguments, and prove it on a "
              "three-head VM")
        print("  before shipping it: docs/Technical.md section 6, "
              "\"Adding a GNOME generation\".")
        return 1
    want = have[shell]
    bad = 0
    if want["tail_slots"] != ints:
        print("  DISAGREES with the record shipped for GNOME %d: it fills %d slots, "
              "this header wants %d" % (shell, want["tail_slots"], ints))
        bad = 1
    if want["struct_size"] != size:
        print("  DISAGREES with the record shipped for GNOME %d: it records %d "
              "bytes, this header lays out %d" % (shell, want["struct_size"], size))
        bad = 1
    if not bad:
        print("  agrees with the record shipped for GNOME %d (%s, %d bytes, %d "
              "4-byte slot%s)" % (shell, want["namespace"], size, ints,
                                  "" if ints == 1 else "s"))
    return bad


FORBIDDEN = ("save", "write", "store", "persist")


def identifiers(text: str) -> list:
    """Every C symbol a type description makes callable."""
    out = []
    for line in text.splitlines():
        i = line.find('c:identifier="')
        if i >= 0:
            out.append(line[i + 14:line.index('"', i + 14)])
    return sorted(set(out))


def gir(record: dict) -> tuple:
    """(namespace, gir text) for one generation record."""
    ns, ints = record["namespace"], record["tail_slots"]
    tail = "".join(TAIL_FIELD.format(off=56 + 4 * i) for i in range(ints))
    text = HEAD.format(gen=record["libmutter"], ns=ns, tail=tail) + BODY
    # the extension must not be *able* to reach Mutter's monitors.xml writer, even
    # by mistake: a symbol that is not described cannot be called from JS at all
    for sym in identifiers(text):
        for bad in FORBIDDEN:
            if bad in sym.lower():
                raise SystemExit("gen-gir: %s makes %s callable" % (ns, sym))
    return ns, text


# -- what a typelib *means*, as against what bytes it happens to be ----------
#
# `--check` used to compare the shipped typelib with a fresh compile byte for
# byte, and that comparison does not survive a compiler upgrade: g-ir-compiler
# 1.86 (Ubuntu 26.04, and nixpkgs) writes a different reserved word into every
# FunctionBlob than the 1.80 that compiled the files checked in here -- 17
# four-byte words per typelib, 0x00000001 against 0x03FF0FFD -- and the two
# 1.86 compilers agree with each other.  Nothing about the description changed:
# all six checks pass live on GNOME 46.0 with the shipped bytes (noble-gnome
# golden, package route).  So the byte hash is printed and decides nothing, and
# what is compared is what the extension actually depends on: the namespace,
# that no shared library is named, every function's name and C symbol, and
# every record's size and field offsets.
#
# It is read back with GIRepository, in a subprocess per typelib, because a
# process has exactly one default repository and two namespaces of the same
# name cannot both be in it.

_DUMP = r"""
import json, sys

try:
    import gi
    for _v in ("3.0", "2.0"):
        try:
            gi.require_version("GIRepository", _v)
            break
        except ValueError:
            pass
    from gi.repository import GIRepository as G
except ImportError:
    # exit 3 and nothing else: "there is no GIRepository on this machine" is a
    # different answer from "this typelib would not load", and a caller that
    # cannot tell them apart passes a broken file.
    raise SystemExit(3)

directory, ns = sys.argv[1], sys.argv[2]
repo = (G.Repository.dup_default() if hasattr(G.Repository, "dup_default")
        else G.Repository.get_default())
repo.prepend_search_path(directory)
repo.require(ns, "1.0", 0)


def kind_of(info):
    # 3.0 subclasses (FunctionInfo, StructInfo, FieldInfo).  2.0 hands back a
    # plain BaseInfo for everything; 26.04's 2.0 binding still answers
    # g_base_info_get_type() with an InfoType whose nick is the kind, but
    # 24.04's (python3-gi 3.48 over girepository 1.80) exposes neither that
    # function nor a get_type method on the info -- measured on noble-kde: dir()
    # is copy/equal/get_attribute/get_container/get_name and nothing more -- so
    # there is no way to tell a struct from a function without calling a
    # struct accessor on what might not be one, which is a C assertion.  That
    # binding cannot read a typelib's meaning: exit 3, the "no GIRepository
    # here" answer, which the callers report as a skip and never as a pass.
    kind = type(info).__name__
    if kind != "BaseInfo":
        return kind
    if hasattr(info, "get_type"):
        t = info.get_type()
    elif hasattr(G, "base_info_get_type"):
        t = G.base_info_get_type(info)
    else:
        raise SystemExit(3)
    nick = getattr(t, "value_nick", None) or str(t).rsplit(".", 1)[-1].lower()
    return nick.replace("_", "").capitalize() + "Info"


def call(obj, name, *args):
    # GIRepository 3.0 made the info accessors methods; 2.0 has them as module
    # functions named <kind>_info_get_<what>.  Both spellings are tried so this
    # reads the same typelib on 24.04 and on 26.04.  `get_caller_owns` is the
    # one that is not named after the info's own kind: it lives on
    # CallableInfo, so 2.0 spells it g_callable_info_get_caller_owns for a
    # FunctionInfo, and the callable fallback is tried after the derived name.
    if hasattr(obj, name):
        return getattr(obj, name)(*args)
    kind = kind_of(obj).replace("Info", "").lower()
    for spelling in ("%s_info_%s" % (kind, name), "callable_info_%s" % name):
        fn = getattr(G, spelling, None)
        if fn is not None:
            return fn(obj, *args)
    raise AttributeError(name)


def shared():
    if hasattr(repo, "get_shared_libraries"):
        return list(repo.get_shared_libraries(ns) or [])
    lib = repo.get_shared_library(ns)
    return [p for p in (lib or "").split(",") if p]


out = {"namespace": ns, "shared_libraries": shared(), "functions": {},
       "records": {}}
for i in range(repo.get_n_infos(ns)):
    info = repo.get_info(ns, i)
    name, kind = info.get_name(), kind_of(info)
    if kind == "FunctionInfo":
        # transfer as well as the symbol: transfer-ownership is the difference
        # between gjs freeing what g_strndup allocated and leaking it once per
        # call, it is invisible in the .gir's neighbours and in every size and
        # offset here, and it is a real difference between two typelibs that
        # describe the same 17 functions.
        out["functions"][name] = {"symbol": call(info, "get_symbol"),
                                  "transfer": int(call(info, "get_caller_owns"))}
    elif kind == "StructInfo":
        fields = {}
        for j in range(call(info, "get_n_fields")):
            f = call(info, "get_field", j)
            fields[f.get_name()] = call(f, "get_offset")
        out["records"][name] = {"size": call(info, "get_size"), "fields": fields}
    else:
        out.setdefault("other", {})[name] = kind
print(json.dumps(out, sort_keys=True))
"""


#: `typelib_summary` could not read the file because this machine has no
#: GIRepository that can tell one info from another (none at all on most
#: desktops; 24.04's 2.0 binding, which exposes no info types) -- a skip, and
#: never a pass.
NO_GIREPOSITORY = "no GIRepository"

#: `--check`'s third exit status, and `_check_meaning`'s: nothing was compared
#: here.  It is not 0, because a caller that cannot tell "agreed" from "did not
#: look" will read the second as the first exactly once, on the day it matters.
SKIPPED = 2


def typelib_summary(directory: str, ns: str):
    """`(summary, why not)` for `<directory>/<ns>-1.0.typelib`.

    `why not` is `NO_GIREPOSITORY` when the bindings are simply absent (which is
    most desktops -- the typelibs are checked in precisely so that nobody needs
    them), and the reader's own stderr when the file is there and will not
    load."""
    rc = subprocess.run([sys.executable, "-c", _DUMP, directory, ns],
                        capture_output=True, text=True)
    if rc.returncode == 3:
        return None, NO_GIREPOSITORY
    if rc.returncode != 0:
        return None, (rc.stderr.strip().splitlines() or ["exit %s" % rc.returncode])[-1]
    try:
        return json.loads(rc.stdout), None
    except ValueError:
        return None, "the reader printed something that is not JSON"


def compare_typelibs(shipped: dict, fresh: dict) -> list:
    """Every way two typelib summaries disagree, one sentence each.  Empty
    means the shipped file describes what the .gir beside it says.

    Namespace, shared libraries, every function's C symbol *and* its return
    transfer, every record's size and every field's offset.  Transfer is in the
    list because it is the only thing the strn fix changed in the shipped bytes
    (`transfer-ownership="none"` -> `"full"`, caller_owns 0 -> 2): a comparison
    without it would have called a typelib that leaks one connector name per
    monitor per read identical to one that does not."""
    bad = []
    if shipped.get("namespace") != fresh.get("namespace"):
        bad.append("namespace %s, not %s"
                   % (shipped.get("namespace"), fresh.get("namespace")))
    for which, s in (("shipped", shipped), ("fresh", fresh)):
        if s.get("shared_libraries"):
            bad.append("the %s typelib names a shared library (%s); a description "
                       "here is a layout and must name none"
                       % (which, ", ".join(s["shared_libraries"])))
    for name in sorted(set(shipped.get("functions", {})) | set(fresh.get("functions", {}))):
        a = shipped.get("functions", {}).get(name) or {}
        b = fresh.get("functions", {}).get(name) or {}
        if a.get("symbol") != b.get("symbol"):
            bad.append("function %s is %s, not %s"
                       % (name, a.get("symbol"), b.get("symbol")))
        if a.get("transfer") != b.get("transfer"):
            bad.append("function %s returns transfer %s, not %s (0 none, 2 full: "
                       "whether the caller owns and frees what it got back)"
                       % (name, a.get("transfer"), b.get("transfer")))
    for name in sorted(set(shipped.get("records", {})) | set(fresh.get("records", {}))):
        a = shipped.get("records", {}).get(name) or {}
        b = fresh.get("records", {}).get(name) or {}
        if a.get("size") != b.get("size"):
            bad.append("%s is %s bytes, not %s" % (name, a.get("size"), b.get("size")))
        for f in sorted(set(a.get("fields", {})) | set(b.get("fields", {}))):
            if a.get("fields", {}).get(f) != b.get("fields", {}).get(f):
                bad.append("%s.%s is at offset %s, not %s"
                           % (name, f, a.get("fields", {}).get(f),
                              b.get("fields", {}).get(f)))
    if shipped.get("other") != fresh.get("other"):
        bad.append("the typelib describes %s, not %s"
                   % (shipped.get("other"), fresh.get("other")))
    return bad


def metadata_shell_versions(table):
    """`metadata.json`'s `shell-version`, derived from the table rather than
    kept beside it.  gnome-shell reads that list to decide whether to load the
    extension at all, so a table that gained a generation and a metadata that
    did not would be an extension that refuses on the release it was just taught
    about -- which is the kind of half-edit this rewrite exists to make
    impossible."""
    return [str(g["shell_major"]) for g in table]


#: the one sentence of metadata.json's description that names versions.  It is
#: generated for the same reason `shell-version` is: it was written by hand
#: saying "46 and 50", and a table that gained a generation left it saying so.
MEASURED_SENTENCE = ("Only GNOME Shell %s have been measured; on anything else "
                     "it refuses.")


def metadata_description(table, current):
    """`description` with its measured-versions sentence brought up to date."""
    majors = [str(g["shell_major"]) for g in table]
    if len(majors) > 1:
        listed = "%s and %s" % (", ".join(majors[:-1]), majors[-1])
    else:
        listed = majors[0]
    want = MEASURED_SENTENCE % listed
    # Replace the old sentence wherever it is, so the rest of the description
    # stays hand-written.  `Only GNOME Shell ... refuses.` is matched as a whole.
    out = re.sub(r"Only GNOME Shell [^.]*? have been measured; on anything "
                 r"else it refuses\.", want, current)
    return out if want in out else "%s %s" % (current.rstrip(), want)


def write_metadata(table, check=False):
    """Rewrite (or, with check, compare) metadata.json's shell-version and the
    sentence of its description that names the measured builds.  Returns 1 when
    either was stale."""
    path = os.path.join(EXT_DIR, "metadata.json")
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    meta = json.loads(text)
    want = metadata_shell_versions(table)
    want_desc = metadata_description(table, meta.get("description", ""))
    if meta.get("shell-version") == want and meta.get("description") == want_desc:
        return 0
    if check:
        if meta.get("shell-version") != want:
            print("stale: %s (shell-version %s, the table says %s)"
                  % (path, meta.get("shell-version"), want))
        else:
            print("stale: %s (the description does not name %s)" % (path, want))
        return 1
    meta["shell-version"] = want
    meta["description"] = want_desc
    # rewritten key by key so the file keeps its order and its formatting
    out = json.dumps(meta, indent=2, ensure_ascii=False) + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(out)
    print("metadata.json  shell-version %s" % want)
    return 0


def main(argv):
    check = "--check" in argv
    for i, a in enumerate(argv):
        if a == "--int" and i + 1 < len(argv):
            SIZES[argv[i + 1]] = (4, 4)
    header = shell = None
    for i, a in enumerate(argv):
        if a == "--from-header" and i + 1 < len(argv):
            header = argv[i + 1]
        if a == "--shell" and i + 1 < len(argv):
            shell = argv[i + 1]
        if a == "--gen":
            raise SystemExit(
                "gen-gir: --gen is gone; the table is keyed by GNOME Shell major "
                "now, so it is --shell 50 rather than --gen 18.  (Through GNOME "
                "50 libmutter's API version was a counter of its own; mutter 51 "
                "made it the GNOME major, and a script that asks for one number "
                "when it means the other invites the wrong answer.)")
    if header:
        return report_header(header, shell)
    args = [a for a in argv if not a.startswith("--")]
    skip = set()
    for i, a in enumerate(argv):
        if a in ("--from-header", "--shell", "--int"):
            skip.add(argv[i + 1] if i + 1 < len(argv) else None)
    args = [a for a in args if a not in skip]
    here = HERE
    table = load_table()
    outdir = args[0] if args else os.path.join(EXT_DIR, "typelib")
    compared = skipped = 0
    os.makedirs(outdir, exist_ok=True)
    bad = write_metadata(table, check)
    for record in table:
        ns, text = gir(record)
        gpath = os.path.join(here, "%s-1.0.gir" % ns)
        tpath = os.path.join(outdir, "%s-1.0.typelib" % ns)
        tmp = tpath + ".new" if check else tpath
        if check:
            if not os.path.exists(gpath) or open(gpath).read() != text:
                print("stale: %s" % gpath)
                bad = 1
        else:
            with open(gpath, "w") as fh:
                fh.write(text)
        subprocess.run(["g-ir-compiler", "--includedir", "/usr/share/gir-1.0",
                        "-o", tmp, gpath], check=True)
        if check:
            old = open(tpath, "rb").read() if os.path.exists(tpath) else b""
            new = open(tmp, "rb").read()
            if old != new:
                # informational, and deliberately not a verdict: see the note
                # above compare_typelibs().
                print("note: %s and a fresh compile differ in bytes (%s != %s); "
                      "compared by meaning below"
                      % (tpath, hashlib.sha256(old).hexdigest()[:12],
                         hashlib.sha256(new).hexdigest()[:12]))
            verdict = _check_meaning(outdir, os.path.dirname(tmp), ns, tpath, tmp)
            if verdict == SKIPPED:
                skipped += 1
            else:
                compared += 1
                bad = max(bad, verdict)
            os.unlink(tmp)
        else:
            print("%s  %s  %s" % (ns, gpath, tpath))
    if check:
        print("--check: %d compared, %d skipped" % (compared, skipped))
        # A skip loses to a stale -- something known wrong outranks something
        # unknown -- and beats an all-clear, which is the whole reason it has a
        # status of its own.
        return 1 if bad else (SKIPPED if skipped else 0)
    return bad


def _check_meaning(shipped_dir, fresh_dir, ns, tpath, tmp) -> int:
    """The semantic half of `--check`, over one namespace: namespace, shared
    libraries, function symbols, return transfer, record sizes and field
    offsets.

    The fresh compile is written next to the shipped one as `<ns>-1.0.typelib.new`,
    which GIRepository will not load, so it is linked into a scratch directory
    under its proper name for the read.  A missing GIRepository is a skip and not
    a pass: it returns SKIPPED (2), which main() carries out to the exit status,
    because "nothing was compared" and "nothing disagreed" are different
    answers."""
    shipped, why = typelib_summary(shipped_dir, ns)
    if why == NO_GIREPOSITORY:
        print("skipped: %s (no GIRepository here to read a typelib with)" % tpath)
        return SKIPPED
    if shipped is None:
        print("stale: %s: it will not load (%s)" % (tpath, why))
        return 1
    with tempfile.TemporaryDirectory(prefix="gen-gir-") as scratch:
        shutil.copyfile(tmp, os.path.join(scratch, "%s-1.0.typelib" % ns))
        fresh, why = typelib_summary(scratch, ns)
    if fresh is None:
        print("stale: %s: the fresh compile will not load (%s)" % (tpath, why))
        return 1
    bad = compare_typelibs(shipped, fresh)
    for line in bad:
        print("stale: %s: %s" % (tpath, line))
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
